OPENAI_API_KEY = "INVALID"
ADMIN_USERNAME = "INVALID"
ADMIN_PASSWORD = "INVALID"
MAIL = "INVALID"
MAIL_PW = "INVALID"
ENABLE_TOOL = "True"
ENABLE_TOOL_DATE = "INVALID"
[connections.gcs]
type = "INVALID"
project_id = "INVALID"
private_key_id = "INVALID"
private_key = "INVALID"
client_email = "INVALID"
client_id = "INVALID"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "INVALID"